### PR TITLE
remove not found tests for kc/kc #412

### PR DESCRIPTION
**Pull request by andrei-panov**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes https://github.tools.sap/kc/kc/issues/412

**Special notes for your reviewer**:

**Release note**:

```improvement operator
partially remove non-existing tests and stop skipping one tests successfully executed with the main cloud providers
```

### CODE REVIEW

**Comment by dguendisch** [comment]
Hi @andrei-panov, is this PR ready for review or are you going to amend changes (I noticed that you pushed more test removals recently to this PR)?

**Comment by andrei-panov** [comment]
Hi @dguendisch 
Sorry for the noise but it's not ready yet. We discuss it yesterday and some more work required.

**Comment by dguendisch** [comment]
No prob, you can just file a draft PR in such cases (I converted this PR now into a draft, just convert it back when it's ready).

**Comment by andrei-panov** [comment]
Hi @dguendisch, it's ready for review.

**Review by dguendisch — APPROVED** [review]
/lgtm

**Comment by andrei-panov** [comment]
Please merge it if it's fine. I don't have permission.

**Pull request merged**
