### PR TITLE
Test case 301 to case 400 - Jc

### PR DESCRIPTION
**Pull request by jguipi**
**What this PR does / why we need it**:
These test cases have been validated success against aws/gcp/azure on k8s 1.20.4, hence moving it from skip.json to working.json
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Review by schrodit — CHANGES_REQUESTED** [review]
> These test cases have been validated success against aws/gcp/azure on k8s 1.20.4, hence moving it from skip.json to working.json
I think you missed to add the testcases in the working.json?
They are just removed from the skip.json.

When you add the testcases can you also check their execution times and categorize them respectively (tests that are faster than 2minutes belong to the `fast` group all others to the `slow` group)

**Comment by jguipi** [comment]
> > These test cases have been validated success against aws/gcp/azure on k8s 1.20.4, hence moving it from skip.json to working.json
> > I think you missed to add the testcases in the working.json?
> > They are just removed from the skip.json.
> 
> When you add the testcases can you also check their execution times and categorize them respectively (tests that are faster than 2minutes belong to the `fast` group all others to the `slow` group)

Done :) !

**Comment by dguendisch** [comment]
Hi @jguipi , are you sure that we go down from ~434 tests in working.json vs now some 34 ones?

**Comment by jguipi** [comment]
> Hi @jguipi , are you sure that we go down from ~434 tests in working.json vs now some 34 ones?

Was missing the data from the upstream. Just merge and rebase it all

**Review by dguendisch — APPROVED** [review]
/lgtm

**Review by schrodit — APPROVED** [review]

**Pull request merged**
