### PR TITLE
Update alpine 3.13 to 3.14

### PR DESCRIPTION
**Pull request by dguendisch**
**How to categorize this PR?**

/area open-source
/kind cleanup

**What this PR does / why we need it**:
Updates base images from alpine 3.13 to 3.14 (which also updates python 3.8 to 3.9) so that newer versions of cicd libs can be installed.

/invite @schrodit
cc @vpnachev 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Review by schrodit — APPROVED** [review]

**Comment by vpnachev** [comment]
If you can ensure this image will run on new enough container runtime (see https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2), I am fine, but I would suggest to keep running on 3.13 for some more months.

**Comment by dguendisch** [comment]
Turns out we do have runtimes with not sufficiently new runc version, hence alpine 3.14 is not an option yet...
/hold

**Comment by dguendisch** [comment]
> Turns out we do have runtimes with not sufficiently new runc version, hence alpine 3.14 is not an option yet...

These runtimes are now upgraded to recent enough runc/docker/libseccomp versions to be able to use alpine 3.14.
/unhold

**Comment by dguendisch** [comment]
cc @ccwienk @jkrayl

**Review by schrodit — APPROVED** [review]
/lgtm

**Pull request merged**
