### PR TITLE
mv pipeline-code from refs/meta/ci:branch.cfg into default-branch

### PR DESCRIPTION
**Pull request by ccwienk**
Move most contents from refs/meta/ci branch.cfg into default branch. Note that there is a corresponding change that should be done alongside of merging this pull-request (cannot be done via GitHub Pull-Request).

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
This PR proposes changes that would break the pipeline definition:
```
<invalid YAML>: found undefined alias 'ti_docker_images'
  in "<unicode string>", line 80, column 13:
            <<: *ti_docker_images
                ^
```

**Comment by gardener-robot-ci-3** [comment]
This PR proposes changes that would break the pipeline definition:
```
<invalid YAML>: found undefined alias 'ti_docker_images'
  in "<unicode string>", line 80, column 13:
            <<: *ti_docker_images
                ^
```

**Comment by gardener-robot-ci-3** [comment]
The pipeline-definition has been fixed.

**Comment by ccwienk** [comment]
> The pipeline-definition has been fixed.

thank you, @gardener-robot-ci-3

**Comment by ccwienk** [comment]
this is the remaining `branch.cfg` we should use after merging this pull-request:

```
cfgs:
  default:
    branches: ['master']

  release-branches:
    branches: ['rel-.*', 'hotfix-.*']
    inherit:
      test-infra:
        jobs:
          release:
            traits:
              version:
                preprocess: 'finalize'
              release:
                nextversion: 'bump_patch'
```

**Comment by ccwienk** [comment]
@dguendisch @hendrikKahl : after merging this pull-request (and updating refs/meta/ci branch.cfg), I will create a second pull-request proposing change from GCR -> Artifact-Registry.
I think it should be easier to do those changes in two separate attempts.

**Review by hendrikKahl — APPROVED** [review]
/lgtm

**Comment by hendrikKahl** [comment]
https://github.com/gardener/test-infra/commit/4cc7ef4e570272e950c805503f8bebb6721f2574 updates the `branch.cfg`.

**Pull request merged**
