### PR TITLE
Vendor gardener@v1.51.0

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area testing
/kind enhancement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/backlog/issues/19

**Special notes for your reviewer**:

**Release note**:

```other operator
The following dependency is updated:
- github.com/gardener/gardener: v1.38.2 -> v1.51.0
```

### CODE REVIEW

**Comment by acumino** [comment]
/invite @hendrikKahl 
some tests will fail I will adapt changes for them tomorrow.

**Comment by hendrikKahl** [comment]
@acumino thanks for the PR!
There is not much to add, but could you please update these images to be in sync with the vendored version of Argo WF?

https://github.com/gardener/test-infra/blob/master/charts/testmachinery/values.yaml#L106-L108

**Review by dguendisch — APPROVED** [review]
/lgtm

**Comment by hendrikKahl** [comment]
@acumino looks like the argo wf v3.3.x introduces a new CRD... sorry, missed that.

Would you mind adding this [CRD](https://github.com/argoproj/argo-workflows/blob/v3.3.8/manifests/base/crds/full/argoproj.io_workflowtaskresults.yaml) to our [chart](https://github.com/gardener/test-infra/blob/master/charts/testmachinery/charts/argo/templates/crds.yaml). Also the [clusterrole](https://github.com/gardener/test-infra/blob/master/charts/testmachinery/charts/argo/templates/rbac.yaml#L149) needs to be extended with [this](https://github.com/argoproj/argo-workflows/blob/v3.3.8/manifests/cluster-install/workflow-controller-rbac/workflow-controller-clusterrole.yaml#L63-L70).

**Pull request merged**
